import type { TestDefinition } from '../../domain/types';
import { rule } from '../../domain/applicability';

export const disclosureTests: TestDefinition[] = [
  {
    id: 'DISC-001',
    vulnerabilityName: 'Verbose Error Messages and Stack Traces',
    category: 'disclosure',
    priority: 'Medium',
    description:
      'Unhandled errors return stack traces, SQL statements, file paths or framework internals that assist an attacker in building further attacks.',
    testingGuidance: [
      'Trigger errors deliberately: malformed types, oversized values, invalid IDs, broken JSON, unexpected verbs.',
      'Inspect both HTML and API error responses, including 500 pages and validation errors.',
      'Record any disclosure of paths, queries, versions or internal hostnames.',
    ],
    owasp: ['WSTG-ERRH-01'],
    cwe: ['CWE-209'],
    applicability: rule.always(),
    tags: ['disclosure'],
  },
  {
    id: 'DISC-002',
    vulnerabilityName: 'Sensitive Information Disclosure in Responses',
    category: 'disclosure',
    priority: 'High',
    description:
      'Responses contain data the requesting user should not see — other users\' records, internal identifiers, credentials, tokens or debug fields.',
    testingGuidance: [
      'Review raw responses for fields not rendered by the UI.',
      'Check search, autocomplete and aggregate endpoints for cross-user leakage.',
      'Look for secrets in JSON metadata, HTML data attributes and JavaScript configuration objects.',
    ],
    owasp: ['A01:2021', 'API3:2023'],
    cwe: ['CWE-200'],
    applicability: rule.always(),
    tags: ['disclosure'],
  },
  {
    id: 'DISC-003',
    vulnerabilityName: 'Sensitive Data in URL Parameters',
    category: 'disclosure',
    priority: 'Medium',
    description:
      'Tokens, credentials, personal data or session identifiers appear in query strings where they are logged by servers, proxies, browser history and Referer headers.',
    testingGuidance: [
      'Review all GET requests for sensitive values, including redirects and third-party callbacks.',
      'Check whether reset/invite tokens leak to analytics via Referer.',
      'Confirm Referrer-Policy limits cross-origin leakage.',
    ],
    owasp: ['WSTG-CONF-*'],
    cwe: ['CWE-598'],
    applicability: rule.always(),
    tags: ['disclosure'],
  },
  {
    id: 'DISC-004',
    vulnerabilityName: 'Source Code and Backup File Disclosure',
    category: 'disclosure',
    priority: 'High',
    description:
      'Backups, editor temp files, archives or misconfigured handlers expose server-side source code containing logic and credentials.',
    testingGuidance: [
      'Request known files with backup suffixes (.bak, .old, ~, .swp, .zip, .tar.gz, .save).',
      'Test handler bypasses that return source instead of executing it (case variation, trailing dot, alternate extension).',
      'Search for exposed repositories or build artefacts on the host.',
    ],
    owasp: ['WSTG-CONF-04'],
    cwe: ['CWE-540', 'CWE-530'],
    applicability: rule.includes('assetTypes', 'web-app', 'rest-api', 'graphql-api', 'soap-api'),
    tags: ['disclosure'],
  },
  {
    id: 'DISC-005',
    vulnerabilityName: 'Internal Network Information Disclosure',
    category: 'disclosure',
    priority: 'Low',
    description:
      'Responses reveal internal IP addresses, hostnames, infrastructure topology or private endpoints useful for lateral movement and SSRF targeting.',
    testingGuidance: [
      'Inspect headers, error pages, redirects and API metadata for RFC1918 addresses and internal DNS names.',
      'Check WSDL/OpenAPI documents and JavaScript configuration for internal service URLs.',
      'Review email headers generated by the application.',
    ],
    owasp: ['WSTG-INFO-*'],
    cwe: ['CWE-200'],
    applicability: rule.always(),
    tags: ['disclosure'],
  },
  {
    id: 'DISC-006',
    vulnerabilityName: 'Metadata Leakage in Files and Documents',
    category: 'disclosure',
    priority: 'Low',
    description:
      'Uploaded or generated files retain EXIF geolocation, author names, internal paths, tracked changes or hidden sheets.',
    testingGuidance: [
      'Download generated reports and user-uploaded media and inspect metadata.',
      'Check whether uploaded images are stripped of EXIF before being served.',
      'Review PDFs and office documents for author, path and revision data.',
    ],
    owasp: ['WSTG-INFO-*'],
    cwe: ['CWE-212'],
    applicability: rule.any(rule.is('hasFileUpload', true), rule.is('hasDataExport', true)),
    tags: ['disclosure', 'privacy'],
  },
  {
    id: 'DISC-007',
    vulnerabilityName: 'Sensitive Data in Client-Side Logs and Telemetry',
    category: 'disclosure',
    priority: 'Medium',
    description:
      'The client logs tokens, credentials or personal data to the console, or forwards them to error-tracking and analytics providers.',
    testingGuidance: [
      'Exercise the application with the console open and record what is logged.',
      'Inspect outbound requests to analytics/error services for personal data and tokens in payloads or URLs.',
      'Check whether the session replay tooling masks form fields.',
    ],
    owasp: ['A09:2021'],
    cwe: ['CWE-532'],
    applicability: rule.includes('assetTypes', 'web-app'),
    tags: ['disclosure', 'privacy'],
  },
  {
    id: 'DISC-008',
    vulnerabilityName: 'User Enumeration via Response Differences',
    category: 'disclosure',
    priority: 'Medium',
    description:
      'Non-authentication features (profile lookup, sharing, invitations, API filters) reveal whether an account, resource or tenant exists.',
    testingGuidance: [
      'Compare responses for existing vs non-existing identifiers across non-login features.',
      'Check status codes, message wording, response length and timing.',
      'Assess whether enumeration enables targeted attacks at scale.',
    ],
    owasp: ['WSTG-IDNT-04'],
    cwe: ['CWE-204'],
    applicability: rule.is('hasAuthentication', true),
    tags: ['disclosure'],
  },
];

export const availabilityTests: TestDefinition[] = [
  {
    id: 'DOS-001',
    vulnerabilityName: 'Missing Rate Limiting',
    category: 'availability',
    priority: 'High',
    description:
      'Sensitive or expensive operations accept unlimited requests from a single client, enabling brute force, scraping, resource exhaustion and cost amplification.',
    testingGuidance: [
      'Baseline the accepted request rate for login, search, OTP, export and API endpoints.',
      'Test limits per IP, per account and per token, and check whether they can be reset by rotating identifiers.',
      'Confirm limits are enforced server-side and return an appropriate 429 rather than failing open.',
    ],
    owasp: ['API4:2023', 'WSTG-BUSL-05'],
    cwe: ['CWE-770'],
    applicability: rule.always(),
    tags: ['rate-limiting'],
  },
  {
    id: 'DOS-002',
    vulnerabilityName: 'Account Lockout Denial of Service',
    category: 'availability',
    priority: 'Medium',
    description:
      'An aggressive lockout policy lets an attacker disable arbitrary user accounts by submitting failed logins on their behalf.',
    testingGuidance: [
      'Trigger lockout on a controlled account and measure the duration and unlock path.',
      'Assess whether lockout can be applied at scale to many accounts.',
      'Check whether adaptive controls (CAPTCHA, delays) are used instead of hard lockout.',
    ],
    owasp: ['WSTG-ATHN-03'],
    cwe: ['CWE-645'],
    applicability: rule.is('hasAuthentication', true),
    tags: ['rate-limiting'],
  },
  {
    id: 'DOS-003',
    vulnerabilityName: 'Resource Exhaustion via Large or Complex Payloads',
    category: 'availability',
    priority: 'Medium',
    description:
      'The application accepts oversized bodies, deeply nested structures, XML/zip bombs or huge parameter counts, exhausting CPU or memory.',
    testingGuidance: [
      'Submit progressively larger bodies and deeply nested JSON/XML and measure response behaviour.',
      'Test archive and XML expansion where the server processes such content.',
      'Confirm limits exist at the gateway and in the application.',
    ],
    owasp: ['WSTG-BUSL-*'],
    cwe: ['CWE-400'],
    applicability: rule.always(),
    tags: ['dos'],
  },
  {
    id: 'DOS-004',
    vulnerabilityName: 'Regular Expression Denial of Service (ReDoS)',
    category: 'availability',
    priority: 'Medium',
    description:
      'Input validated by a catastrophically backtracking regular expression allows a small request to consume disproportionate CPU.',
    testingGuidance: [
      'Identify fields with pattern validation (email, URL, phone, custom formats).',
      'Submit crafted strings that trigger backtracking and measure response time growth.',
      'Where source is available, review regexes for nested quantifiers.',
    ],
    owasp: ['WSTG-*'],
    cwe: ['CWE-1333'],
    applicability: rule.always(),
    tags: ['dos'],
  },
  {
    id: 'DOS-005',
    vulnerabilityName: 'Expensive Query and Unbounded Pagination',
    category: 'availability',
    priority: 'Medium',
    description:
      'Search, reporting and listing endpoints allow unbounded result sets, wildcard queries or costly sorts that degrade the service.',
    testingGuidance: [
      'Request maximum/absent page sizes and wildcard-only searches.',
      'Test sorting and filtering on unindexed fields and cross-joins via nested expansion.',
      'Measure server response degradation and note any caps discovered.',
    ],
    owasp: ['API4:2023'],
    cwe: ['CWE-405'],
    applicability: rule.any(rule.is('hasSearch', true), rule.is('hasDataExport', true)),
    tags: ['dos'],
  },
  {
    id: 'DOS-006',
    vulnerabilityName: 'Notification Flooding (Email / SMS Bombing)',
    category: 'availability',
    priority: 'Medium',
    description:
      'Unthrottled notification triggers let an attacker send unlimited messages to a victim address or phone number, causing harassment and direct cost.',
    testingGuidance: [
      'Repeatedly trigger registration, password reset, OTP and invitation messages for a controlled address.',
      'Measure per-recipient throttling and cooldown enforcement.',
      'Check whether the recipient address can be attacker-supplied for arbitrary targets.',
    ],
    owasp: ['WSTG-BUSL-05'],
    cwe: ['CWE-770'],
    applicability: rule.is('hasEmailNotifications', true),
    tags: ['dos'],
  },
];

export const privacyTests: TestDefinition[] = [
  {
    id: 'PRIV-001',
    vulnerabilityName: 'Excessive Personal Data Collection and Retention',
    category: 'privacy',
    priority: 'Medium',
    description:
      'The application collects or retains more personal data than the function requires, or keeps it indefinitely, increasing breach impact and regulatory exposure.',
    testingGuidance: [
      'Compare collected fields against the stated purpose of each feature.',
      'Check whether deleted accounts and records are actually purged or only soft-deleted.',
      'Review retention of logs, backups and analytics containing personal data.',
    ],
    owasp: ['A02:2021'],
    cwe: ['CWE-359'],
    applicability: rule.is('handlesPii', true),
    tags: ['privacy'],
  },
  {
    id: 'PRIV-002',
    vulnerabilityName: 'Personal Data Leakage to Third Parties',
    category: 'privacy',
    priority: 'High',
    description:
      'Personal or sensitive data is transmitted to analytics, advertising, session replay or support vendors, often through URLs, form capture or replay tooling.',
    testingGuidance: [
      'Monitor outbound requests while using authenticated flows and inspect payloads.',
      'Check session replay masking on forms containing personal or payment data.',
      'Confirm data sharing is disclosed and consented to.',
    ],
    owasp: ['A02:2021'],
    cwe: ['CWE-359'],
    applicability: rule.all(rule.is('handlesPii', true), rule.is('usesThirdPartyScripts', true)),
    tags: ['privacy'],
  },
  {
    id: 'PRIV-003',
    vulnerabilityName: 'Missing Consent and Tracking Controls',
    category: 'privacy',
    priority: 'Low',
    description:
      'Tracking technologies are set before consent, consent cannot be withdrawn, or rejecting consent does not stop data collection.',
    testingGuidance: [
      'Load the site with a clean profile and record cookies/storage set before any interaction.',
      'Reject consent and confirm trackers are not loaded.',
      'Test whether the withdrawal mechanism works and persists.',
    ],
    owasp: ['-'],
    cwe: ['CWE-359'],
    applicability: rule.all(rule.includes('assetTypes', 'web-app'), rule.is('handlesPii', true)),
    tags: ['privacy'],
  },
  {
    id: 'PRIV-004',
    vulnerabilityName: 'Unmasked Sensitive Data in Interface and Exports',
    category: 'privacy',
    priority: 'Medium',
    description:
      'Full card numbers, national IDs, health details or credentials are displayed or exported in clear where masking is expected.',
    testingGuidance: [
      'Review screens, print views, exports and emails for unmasked sensitive values.',
      'Check API responses behind masked UI fields — masking is often client-side only.',
      'Test whether support/admin roles see more than they require.',
    ],
    owasp: ['A02:2021'],
    cwe: ['CWE-201'],
    applicability: rule.any(rule.is('handlesPii', true), rule.is('handlesPayments', true), rule.is('handlesHealthData', true)),
    tags: ['privacy'],
  },
  {
    id: 'PRIV-005',
    vulnerabilityName: 'Cardholder Data Handling Weakness',
    category: 'privacy',
    priority: 'High',
    description:
      'Card data is stored, logged or transmitted outside a compliant boundary — full PAN retention, CVV storage, or card data flowing through the application rather than a tokenised provider.',
    testingGuidance: [
      'Trace the card data flow: does it touch the application server or go directly to the processor?',
      'Search responses, logs and storage for PAN patterns and CVV values.',
      'Verify masking rules (first six/last four) and confirm CVV is never persisted.',
    ],
    owasp: ['A02:2021'],
    cwe: ['CWE-311'],
    applicability: rule.is('handlesPayments', true),
    tags: ['privacy', 'pci'],
  },
  {
    id: 'PRIV-006',
    vulnerabilityName: 'Insufficient Data Subject Rights Support',
    category: 'privacy',
    priority: 'Low',
    description:
      'There is no working mechanism for access, correction, export or deletion of personal data, or the mechanism itself leaks data to unverified requesters.',
    testingGuidance: [
      'Exercise any self-service data export/deletion function and verify completeness.',
      'Test identity verification on such requests — these endpoints are a common IDOR target.',
      'Confirm exported bundles do not include other users\' data.',
    ],
    owasp: ['-'],
    cwe: ['CWE-359'],
    applicability: rule.is('handlesPii', true),
    tags: ['privacy'],
  },
];
