/**
 * VAPT Checklist — Excel export model
 * ---------------------------------------------------------------------------
 * Generated entirely client-side with `write-excel-file` (bundled, no CDN).
 *
 * The workbook is a deliverable, not a data dump. It is built from the same
 * ChecklistItem[] + EngagementMetrics the dashboard uses, so the spreadsheet
 * can never disagree with the screen.
 *
 * Sheets
 *   1. Summary            engagement identity + coverage metrics
 *   2. Checklist          every applicable test with status, result, notes
 *   3. Findings           vulnerable tests only, ordered by priority
 *   4. Not Applicable     excluded tests + why (audit trail of scope decisions)
 *   5. Application Context recorded facts that drove applicability
 *   6. Coverage by Category
 */

import writeXlsxFile, {
  type CellObject,
  type Row,
  type Sheet,
  type SheetData,
} from 'write-excel-file/browser';
import { CATEGORY_BY_ID } from '../data/categories';
import { LIBRARY_VERSION } from '../data/library';
import { describeRule, suggestApplicability } from '../domain/applicability';
import { CONTEXT_FACTS, CONTEXT_SECTIONS, formatFactValue } from '../domain/context';
import { collectFindings, computeMetrics } from '../domain/metrics';
import type { ChecklistItem, Engagement, Priority } from '../domain/types';
import { buildFileName } from './fileName';

/* ------------------------------------------------------------------ styling */

const INK = '#0F172A';
const HEADER_BG = '#0F172A';
const HEADER_FG = '#FFFFFF';
const BAND = '#F1F5F9';
const BORDER = '#CBD5E1';

const PRIORITY_BG: Record<Priority, string> = {
  Critical: '#FEE2E2',
  High: '#FFEDD5',
  Medium: '#FEF9C3',
  Low: '#E0F2FE',
};

const RESULT_BG: Record<string, string> = {
  Vulnerable: '#FEE2E2',
  'Not Vulnerable': '#DCFCE7',
};

type Cell = CellObject;

const title = (value: string, columnSpan?: number): Cell => ({
  value,
  fontWeight: 'bold',
  fontSize: 14,
  textColor: INK,
  columnSpan,
});

const header = (value: string): Cell => ({
  value,
  fontWeight: 'bold',
  textColor: HEADER_FG,
  backgroundColor: HEADER_BG,
  align: 'left',
  alignVertical: 'center',
  wrap: true,
  borderColor: BORDER,
});

const label = (value: string): Cell => ({
  value,
  fontWeight: 'bold',
  textColor: INK,
  backgroundColor: BAND,
  borderColor: BORDER,
  alignVertical: 'top',
});

const text = (value: string | undefined, extra: Partial<Cell> = {}): Cell => ({
  value: value ?? '',
  type: String,
  wrap: true,
  alignVertical: 'top',
  borderColor: BORDER,
  ...extra,
});

const num = (value: number, extra: Partial<Cell> = {}): Cell => ({
  value,
  type: Number,
  borderColor: BORDER,
  ...extra,
});

const pct = (value: number): Cell => ({
  value: Math.round(value * 1000) / 1000,
  type: Number,
  format: '0.0%',
  borderColor: BORDER,
});

const blank: Cell = { value: '', type: String };

/* ---------------------------------------------------------------- sheet 1 */

function summarySheet(
  engagement: Engagement,
  items: ChecklistItem[],
  metrics: ReturnType<typeof computeMetrics>,
): SheetData {
  const c = metrics.counts;
  const rows: SheetData = [
    [title('VAPT Assessment Report', 4)],
    [text('Generated by VAPT Checklist', { textColor: '#64748B' })],
    [],
    [label('Engagement'), text(engagement.name, { columnSpan: 3 })],
    [label('Client'), text(engagement.clientName ?? '-', { columnSpan: 3 })],
    [label('Tester'), text(engagement.testerName ?? '-', { columnSpan: 3 })],
    [label('Status'), text(engagement.status, { columnSpan: 3 })],
    [
      label('Assessment period'),
      text(`${engagement.startDate ?? '-'} to ${engagement.endDate ?? '-'}`, { columnSpan: 3 }),
    ],
    [label('Scope'), text(engagement.scope.join('\n') || '-', { columnSpan: 3 })],
    [label('Description'), text(engagement.description ?? '-', { columnSpan: 3 })],
    [label('Exported at'), text(new Date().toISOString(), { columnSpan: 3 })],
    [label('Test library version'), text(LIBRARY_VERSION, { columnSpan: 3 })],
    [],
    [title('Coverage', 4)],
    [header('Metric'), header('Count'), header('Metric'), header('Count')],
    [label('Tests in library'), num(c.total), label('Applicable'), num(c.applicable)],
    [label('Not applicable'), num(c.excluded), label('Not tested'), num(c.notTested)],
    [label('Tested'), num(c.tested), label('Marked N/A'), num(c.na)],
    [label('Vulnerable'), num(c.vulnerable), label('Not vulnerable'), num(c.notVulnerable)],
    [label('Awaiting result'), num(c.awaitingResult), label('Manual applicability overrides'), num(metrics.manualOverrides)],
    [label('Completion'), pct(metrics.completion), label('Vulnerable rate'), pct(metrics.vulnerableRate)],
    [],
    [title('Findings by Priority', 4)],
    [header('Priority'), header('Findings'), header('Outstanding tests'), header('Applicable')],
  ];

  for (const p of ['Critical', 'High', 'Medium', 'Low'] as Priority[]) {
    const group = metrics.byPriority.find((g) => g.key === p);
    rows.push([
      text(p, { fontWeight: 'bold', backgroundColor: PRIORITY_BG[p] }),
      num(metrics.findingsByPriority[p]),
      num(metrics.outstandingByPriority[p]),
      num(group?.counts.applicable ?? 0),
    ]);
  }

  const findings = collectFindings(items);
  rows.push([], [title('Findings Overview', 4)]);
  if (findings.length === 0) {
    rows.push([text('No vulnerabilities recorded.', { columnSpan: 4, textColor: '#15803D' })]);
  } else {
    rows.push([header('ID'), header('Vulnerability'), header('Priority'), header('Category')]);
    for (const f of findings) {
      rows.push([
        text(f.definition.id),
        text(f.definition.vulnerabilityName),
        text(f.definition.priority, { backgroundColor: PRIORITY_BG[f.definition.priority] }),
        text(CATEGORY_BY_ID[f.definition.category]?.name ?? f.definition.category),
      ]);
    }
  }

  return rows;
}

/* ---------------------------------------------------------------- sheet 2 */

const CHECKLIST_HEADERS = [
  'Test ID',
  'Vulnerability Name',
  'Category',
  'Subcategory',
  'Priority',
  'Status',
  'Result',
  'Notes',
  'Description',
  'Testing Guidance',
  'Also Known As',
  'Applicability',
  'OWASP / Standard',
  'CWE',
  'Last Updated',
];

function checklistRow(item: ChecklistItem, engagement: Engagement): Row {
  const { definition: d, state: s } = item;
  const suggestion = suggestApplicability(d, engagement.context);
  const applicability =
    s.applicabilitySource === 'manual'
      ? 'Included by tester (manual override)'
      : suggestion.summary;
  return [
    text(d.id, { fontWeight: 'bold' }),
    text(d.vulnerabilityName, { fontWeight: 'bold' }),
    text(CATEGORY_BY_ID[d.category]?.name ?? d.category),
    text(d.subcategory),
    text(d.priority, { backgroundColor: PRIORITY_BG[d.priority], align: 'center' }),
    text(s.status, { align: 'center' }),
    text(s.result ?? '', {
      align: 'center',
      backgroundColor: s.result ? RESULT_BG[s.result] : undefined,
      fontWeight: s.result === 'Vulnerable' ? 'bold' : undefined,
    }),
    text(s.notes),
    text(d.description),
    text(d.testingGuidance.map((g, i) => `${i + 1}. ${g}`).join('\n')),
    text((d.aliases ?? []).join(', ')),
    text(applicability),
    text((d.owasp ?? []).join(', ')),
    text((d.cwe ?? []).join(', ')),
    text(s.status === 'Not Tested' && !s.notes ? '' : s.updatedAt.slice(0, 19).replace('T', ' ')),
  ];
}

function checklistSheet(items: ChecklistItem[], engagement: Engagement): SheetData {
  const applicable = items.filter((i) => i.state.applicable);
  return [CHECKLIST_HEADERS.map(header), ...applicable.map((i) => checklistRow(i, engagement))];
}

/* ---------------------------------------------------------------- sheet 3 */

function findingsSheet(items: ChecklistItem[]): SheetData {
  const findings = collectFindings(items);
  const headers = [
    'Test ID',
    'Vulnerability Name',
    'Priority',
    'Category',
    'Subcategory',
    'Notes / Observation',
    'Description',
    'OWASP / Standard',
    'CWE',
    'Recorded',
  ].map(header);

  if (findings.length === 0) {
    return [
      headers,
      [text('No vulnerabilities were recorded for this engagement.', { columnSpan: 10 })],
    ];
  }

  return [
    headers,
    ...findings.map(({ definition: d, state: s }): Row => [
      text(d.id, { fontWeight: 'bold' }),
      text(d.vulnerabilityName, { fontWeight: 'bold' }),
      text(d.priority, { backgroundColor: PRIORITY_BG[d.priority], align: 'center' }),
      text(CATEGORY_BY_ID[d.category]?.name ?? d.category),
      text(d.subcategory),
      text(s.notes),
      text(d.description),
      text((d.owasp ?? []).join(', ')),
      text((d.cwe ?? []).join(', ')),
      text((s.testedAt ?? s.updatedAt).slice(0, 19).replace('T', ' ')),
    ]),
  ];
}

/* ---------------------------------------------------------------- sheet 4 */

function notApplicableSheet(engagement: Engagement, items: ChecklistItem[]): SheetData {
  const excluded = items.filter((i) => !i.state.applicable);
  const headers = [
    'Test ID',
    'Vulnerability Name',
    'Category',
    'Subcategory',
    'Priority',
    'Excluded By',
    'Applicability Rule',
    'Reason',
  ].map(header);

  if (excluded.length === 0) {
    return [
      headers,
      [text('No tests were excluded — the full library was assessed.', { columnSpan: 8 })],
    ];
  }

  return [
    headers,
    ...excluded.map(({ definition: d, state: s }): Row => {
      const suggestion = suggestApplicability(d, engagement.context);
      return [
        text(d.id),
        text(d.vulnerabilityName),
        text(CATEGORY_BY_ID[d.category]?.name ?? d.category),
        text(d.subcategory),
        text(d.priority, { backgroundColor: PRIORITY_BG[d.priority], align: 'center' }),
        text(s.applicabilitySource === 'manual' ? 'Tester (manual)' : 'Context rule (auto)'),
        text(describeRule(d.applicability)),
        text(suggestion.reasons.join('; ')),
      ];
    }),
  ];
}

/* ---------------------------------------------------------------- sheet 5 */

function contextSheet(engagement: Engagement): SheetData {
  const rows: SheetData = [
    [title('Application Context', 3)],
    [text('Facts recorded for this engagement. These drive test applicability.', { columnSpan: 3, textColor: '#64748B' })],
    [],
  ];

  for (const section of CONTEXT_SECTIONS) {
    const facts = CONTEXT_FACTS.filter((f) => f.section === section.id);
    if (facts.length === 0) continue;
    rows.push([header(section.title), header('Value'), header('Notes')]);
    for (const fact of facts) {
      const value = engagement.context[fact.key];
      const unknown = value === undefined || (Array.isArray(value) && value.length === 0);
      rows.push([
        label(fact.label),
        text(formatFactValue(fact.key, value), {
          textColor: unknown ? '#B45309' : INK,
          fontWeight: unknown ? undefined : 'bold',
        }),
        text(fact.hint ?? '', { textColor: '#64748B' }),
      ]);
    }
    rows.push([blank]);
  }

  return rows;
}

/* ---------------------------------------------------------------- sheet 6 */

function coverageSheet(metrics: ReturnType<typeof computeMetrics>): SheetData {
  const headers = [
    'Category',
    'Applicable',
    'Not Tested',
    'Tested',
    'N/A',
    'Vulnerable',
    'Not Vulnerable',
    'Completion',
  ].map(header);

  const rows = metrics.byCategory.map((g): Row => [
    text(g.label, { fontWeight: 'bold' }),
    num(g.counts.applicable),
    num(g.counts.notTested),
    num(g.counts.tested),
    num(g.counts.na),
    num(g.counts.vulnerable, {
      backgroundColor: g.counts.vulnerable > 0 ? RESULT_BG.Vulnerable : undefined,
    }),
    num(g.counts.notVulnerable),
    pct(g.completion),
  ]);

  const c = metrics.counts;
  rows.push([
    text('TOTAL', { fontWeight: 'bold', backgroundColor: BAND }),
    num(c.applicable, { fontWeight: 'bold', backgroundColor: BAND }),
    num(c.notTested, { fontWeight: 'bold', backgroundColor: BAND }),
    num(c.tested, { fontWeight: 'bold', backgroundColor: BAND }),
    num(c.na, { fontWeight: 'bold', backgroundColor: BAND }),
    num(c.vulnerable, { fontWeight: 'bold', backgroundColor: BAND }),
    num(c.notVulnerable, { fontWeight: 'bold', backgroundColor: BAND }),
    pct(metrics.completion),
  ]);

  return [headers, ...rows];
}

/* ------------------------------------------------------------------- entry */

const W = (widths: number[]) => widths.map((width) => ({ width }));

export interface ExportOptions {
  includeNotApplicable?: boolean;
  includeContext?: boolean;
  includeCoverage?: boolean;
  includeFindings?: boolean;
  fileName?: string;
}

export async function exportEngagementToExcel(
  engagement: Engagement,
  items: ChecklistItem[],
  options: ExportOptions = {},
): Promise<string> {
  const {
    includeNotApplicable = true,
    includeContext = true,
    includeCoverage = true,
    includeFindings = true,
  } = options;

  const metrics = computeMetrics(items);

  const sheets: SheetData[] = [
    summarySheet(engagement, items, metrics),
    checklistSheet(items, engagement),
  ];
  const names: string[] = ['Summary', 'Checklist'];
  const columns = [
    W([28, 22, 22, 22]),
    W([10, 34, 20, 22, 10, 12, 14, 46, 60, 70, 34, 42, 18, 14, 18]),
  ];

  if (includeFindings) {
    sheets.push(findingsSheet(items));
    names.push('Findings');
    columns.push(W([10, 34, 10, 20, 22, 50, 60, 18, 14, 18]));
  }
  if (includeNotApplicable) {
    sheets.push(notApplicableSheet(engagement, items));
    names.push('Not Applicable');
    columns.push(W([10, 34, 20, 22, 10, 18, 40, 50]));
  }
  if (includeContext) {
    sheets.push(contextSheet(engagement));
    names.push('Application Context');
    columns.push(W([38, 32, 50]));
  }
  if (includeCoverage) {
    sheets.push(coverageSheet(metrics));
    names.push('Coverage');
    columns.push(W([28, 12, 12, 10, 8, 12, 14, 12]));
  }

  const fileName = options.fileName ?? buildFileName(engagement);

  const workbook: Sheet<Blob>[] = sheets.map((data, index) => ({
    data,
    sheet: names[index],
    columns: columns[index],
    stickyRowsCount: index === 0 ? 0 : 1,
  }));

  await writeXlsxFile(workbook).toFile(fileName);

  return fileName;
}
